USE master;
PRINT '=== SOURCE_CHECKDB_PHYSICAL_ONLY ===';
DBCC CHECKDB(N'WideWorldImporters') WITH PHYSICAL_ONLY, NO_INFOMSGS;
PRINT 'SOURCE_CHECKDB_PHYSICAL_ONLY=PASS';
PRINT '=== MASTER_BACKUP_VERIFYONLY ===';
RESTORE VERIFYONLY FROM DISK=N'/var/opt/mssql/data/wwi-full-master-2026-09-15.bak' WITH CHECKSUM;
PRINT 'MASTER_BACKUP_VERIFYONLY=PASS';
